resources:
  - ../../base
  - patch-envs.yaml
  - ingress.yaml

# Replicas can be adjusted here if needed
# images can be updated here
images:
  - name: avalon-server
    newName: your-registry/avalon-server
    newTag: latest
